sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
matrix:
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
script: npm test --coverage
after_script: codeclimate-test-reporter < coverage/lcov.info
